{% set name = "jmespath" %}
{% set version = "0.9.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "54c441e2e08b23f12d7fa7d8e6761768c47c969e6aed10eead57505ba760aee9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - jmespath


about:
  home: https://github.com/jmespath/jmespath.py
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'JSON Matching Expressions'
  dev_url: https://github.com/jmespath/jmespath.py

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
