travis:
  secure:
    BINSTAR_TOKEN: FyaghFdKmbS+XvsHCpVkEz99S5OLyTlhNB57abH5Gaa3xvJI6oZ5shCKfgkiCIjmEcLJG94RyFbnmQ1g6MeZ6GqBkiwAAPb9GFCnNW/MdPwiuKMSPppAffCCt1BPxVn0LijX6FKwGu5omHb28GpR/Tf5ZIoto9/DXicN0lhLl/aJvLfSx4WNF5bTnwLm+NpslmvfeQbXQIrc4n/NWYXQ5LYci0/jyUKCpiJ66qNVd7BDBbtpva6qUa0AqLDqfrmTw+PhKminYUbVNgPa78bMyS2l8s9kwviZOVgCxqnghF+dwN4/rrBwW+FldPGTGJVL+6EXWIFIpRpnQLcqWuei6AhajPLXgKejf8BGhtyfUoXBbwXHc4CZMf40I/ZeVkWn5h7WirftNlIgg4mU/rYIYO+wmNM3r+kdnOvFSveXgc6rlZuLQkE1x8EA+eiT3iWi3gi0yjxoFOROK065p0JtF3dwuC9aTpubCv4ciOJbp+SrFzE0sIeWAALjWbaGoWuQCBg9bIPxn43mC5PlUlx6AxnzCyjzei70TEeJUCPWnQo3mhc/QIlux5+0GbJqOFRjwpRf2awYOmBbKMjDUcGVicofHwpQc0DmzKay6ZMKKC10tdhV28BtTWt7oK0oU8d+zSJIxtrIkM9h/3WtOmsaJ8UBGRA9lJeTrCSWmXGFveM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
